name: safe_swap
description: "A new Flutter project for community item swapping."
publish_to: 'none' # This project is private and not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # Compatible with Flutter SDK version 3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: any          # Allow the latest version
  provider: any
  image_picker: any
  uuid: any
  supabase_flutter: any
  image: any         
  hive: ^2.0.0
  hive_flutter: ^1.1.0        # For processing and resizing images

dev_dependencies:
  flutter_test:
    sdk: flutter                # For running widget and unit tests
  flutter_lints: ^5.0.0  
  hive_generator: ^2.0.1
  build_runner: ^2.0.0 
  flutter_launcher_icons: ^0.9.3      # For linting and maintaining clean code

flutter:
  uses-material-design: true    # Enables Material Design icons

  # Include app assets like images or fonts
  assets:
    - assets/logo.png           # Example logo image for the app
    # Add other asset paths here if needed
